### ISSUE TITLE
Unable to build dgidb

### ISSUE THREAD

**Issue by SilenWang** [dgidb/dgidb#573] opened 2021-04-11 17:32 UTC
Hello, 
I'm trying to build dgidb locally according to guidence in INSTALL-LINUX.
And when it came to `rake dgidb:load_local`, I got these errors:

```
git submodule update --init data
Cloning into 'data'...
^[[Cfatal: unable to connect to git.genomedata.org:
git.genomedata.org[0: 52.35.40.249]: errno=Connection timed out

Clone of 'git://git.genomedata.org/dgidb_data.git' into submodule path 'data' failed
Unable to access the git repo, you are probably outside our firewall.
Downloading the data dump manually.
wget -O /home/dgidb/dgidb/data/data.sql http://dgidb.org/downloads/data.sql
--2021-04-11 17:04:07--  http://dgidb.org/downloads/data.sql
Resolving dgidb.org (dgidb.org)... 35.167.156.177
Connecting to dgidb.org (dgidb.org)|35.167.156.177|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://dgidb.org/downloads/data.sql [following]
--2021-04-11 17:04:08--  https://dgidb.org/downloads/data.sql
Connecting to dgidb.org (dgidb.org)|35.167.156.177|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-11 17:04:09 ERROR 404: Not Found.

rake aborted!
Failed trying to wget -O /home/dgidb/dgidb/data/data.sql http://dgidb.org/downloads/data.sql in /home/dgidb/dgidb
/home/dgidb/dgidb/lib/utils/snapshot_helpers.rb:61:in `system_or_die'
/home/dgidb/dgidb/lib/utils/snapshot_helpers.rb:55:in `download_data_dump'
/home/dgidb/dgidb/lib/tasks/db_bootstrapping.rake:52:in `rescue in block (2 levels) in <top (required)>'
/home/dgidb/dgidb/lib/tasks/db_bootstrapping.rake:47:in `block (2 levels) in <top (required)>'

Caused by:
Failed trying to git submodule update --init data in /home/dgidb/dgidb
/home/dgidb/dgidb/lib/utils/snapshot_helpers.rb:61:in `system_or_die'
/home/dgidb/dgidb/lib/utils/snapshot_helpers.rb:48:in `update_data_submodule'
/home/dgidb/dgidb/lib/tasks/db_bootstrapping.rake:48:in `block (2 levels) in <top (required)>'
Tasks: TOP => dgidb:load_local
```

Is there anyway to solve this?

**Comment by ahwagner** [comment] 2021-04-12 14:13
Fix in progress. Duplicate of #572.

**Closed by ahwagner** 2021-04-12 14:13 UTC
Labels: duplicate
